export { default as Footer } from './footer/footer.vue'
export { default as FormStatus } from './form-status/form-status.vue'
export { default as Input } from './input/input.vue'
export { default as LoginHeader } from './login-header/login-header.vue'
export { default as Logo } from './logo/logo.vue'
export { default as Spinner } from './spinner/spinner.vue'